USE ItRootsDB;

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Username NVARCHAR(50) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Phone NVARCHAR(15) NOT NULL,
    UserType NVARCHAR(10) CHECK (UserType IN ('Admin','User')) NOT NULL DEFAULT('User'),
    IsVerified BIT NOT NULL DEFAULT(0),
    VerificationToken UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID())
);